apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      # Liste der Container, die im Pod laufen sollen (hier nur einer)
      containers:
        - name: server
          #image: cygnetops/multi-server-pgfix-5-11
          image: saho87/multi-server
          ports:
            - containerPort: 5000
          # Definition der Umgebungsvariablen
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379' 
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
              # Secret, dass schon angelegt wurde, wird übergeben
              # name: PGPASSWORD hat nichts mit Secret zu tun
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD